### ISSUE TITLE
sphinx.ext.todo ベースで書式カスタマイザブルな todo 拡張をつくる

### ISSUE THREAD

**Issue by shouh** [shouh/issueet#807]
## 目的
元ネタ https://github.com/sphinx-doc/sphinx/issues/2730

ソースを提示いただいたので、これ理解して作ってみる。

## 情報源
* https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/todo.py

## アドバイス和訳
> sphinx.ext.todo is consist of nodes, directives, config values, writers and event handlers (You can see them in sphinx/ext/todo.py). And you can replace one of them in your extension. so you can customize the output format with replacing writers like following:

todo 拡張は nodes, directives, ... 等の部品から構成されてるよ。部品の一部を自作拡張内で置き換えてやれば改造できるよ。（改造のポテンシャルは君の力次第だけど一般的な力があれば）出力フォーマットを変えることもできるよ。ちなみに Writer ね。

## わからんこととか
* [x] 自作した拡張やどうやって sphinx に組み込むの？
* [x] 組み込んだ拡張はどうやって使用するの？
* [x] todo の書式は `課題: ...` となってるけど、この **「課題」** の部分はどこをいじれば変えられるの？
  * 見た感じソースに直接書いてあるわけではない。localize されてるのかな？
* [x] todolist では `(元のエントリ は、 c:\....rst の n 行目です)` という表記も出るけど、この部分もどこいじれば変えられるの？

## :x: 見解
ポテンシャルが無くて不可能。

ただしソースを精読すれば、ポテンシャルがある or 抜け道があることがわかるかもしれない。精読できれば。

**Comment by shouh** [comment]
## メモ
肝はここっぽいな。

```
    app.add_node(todo_node,
                 html=(my_visit_todo_node, my_depart_todo_node),
```

**Comment by shouh** [comment]
## 「書式」の差異
提示いただいたサンプルからは **「装飾の話だろ？」** と読み取れる。

俺はどうだっけ？…… **表示されている文字列について、自分の好きな文字列を設定したい** かな。装飾ではない。

……となれば、提示サンプルは装飾に対する解であって、俺の文字列変更には効果無しかも？

**Comment by shouh** [comment]
# 「課題」の文字列はどこにある？
https://github.com/sphinx-doc/sphinx/blob/174e61fdb2fef4859b0b93abc139675f0e25dda5/sphinx/locale/ja/LC_MESSAGES/sphinx.po の 472-474 行目。

```
#: sphinx/ext/todo.py:56
msgid "Todo"
msgstr "課題"
```

**Comment by shouh** [comment]
## Sphinx 拡張についてお勉強するぜい
ネタはこれな http://docs.sphinx-users.jp/extensions.html

**Comment by shouh** [comment]
## tk0miya さんサンプル動かしてみる
まず俺の sphinx プロジェクトはこうなってる。

```
$ cd C:\work\hoge_document\source
$ ls
_static
_template
conf.py
index.rst
sec1.rst
sec2.rst
```

これに対して、以下のように変更を加えてみた。

```
$ cd
C:\work\hoge_document\source
$ ls
_ext  # <-- これ作った
conf.py
mytodo_user.rst # <-- ここに .. mytodo:: を記述した
```

んで _ext フォルダの中には、tk0miya さんサンプルの内容まんま(utf-8 の shibang 書いたけど)を `mytodo.py` って名前で保存。あと空ファイルの `__init__.py` もつくる。

**Comment by shouh** [comment]
## 結論: たぶん無理
俺がやるべきなのは、本質的にいえば 「sphinx.ext.todo に元から備わってる、課題文字列や元のエントリ文字列を生成するプロセスについて、そのプロセスに入る前に、そのプロセスが使用する該当変数の値を、外部(独自拡張)から書き換えられるかどうか」ってこと。

もっといえば、その「そのプロセスが使用する該当変数の値」が、「外部から俺を書き換えてもいいですよ」という口を持っていて、かつその口に外部からアクセスできるようになっているかどうかという話に帰着される。

……見た感じ、そんなポテンシャルは無さそうなんだよなあ。まあ全部厳密に把握できたわけじゃない（しできるはずもない。それができるなら俺はもっとエンジニアやってる）けど。
