### ISSUE TITLE
winsort - window manager prototype

### ISSUE THREAD

**Issue by shouh** [shouh/issueet#933]
based on https://github.com/shouh/zakky/blob/master/dev/tool/window_manager.md

これまでの案

* 案1: がっつり management(**制御は全部システムに任せる**)
* 案2: push, pull, insert ベース(**システムが制御するがどう制御するかは利用者が手動でサクサク行う**)
* 案3: trigger based(`if COND then ACTION` を連ねる)
* 案4: ffresize(ffphrase のウィンドウ操作版＆表示状態記録/復元機能)

現状: 手を動かしてないのでいつまで経っても机上の空論。いいかげん動かすぞ。 → 動かせるようにもっとシンプル設計にする → した https://github.com/shouh/scripts/blob/master/pathed_commands/winsort.py → もうちょっと強化したいね

# todo
* -------- slot --------
* [x] デスクトップのホイールドラッグ
* [x] コーナーインマウスの検出
* [X] ウィンドウを並べるアルゴリズム
  * 最低限でけた https://github.com/shouh/scripts/commit/ba477055d68fb807b5853f3caec4770aefa5e8cb 
  * [x] 画面外のウィンドウを目視し簡単に元に戻す方法(これないと手動で試すのがだるい)
* [x] デスクトップのホイールクリック 汚いがフラグ使ってでけた https://github.com/shouh/scripts/commit/cfe7a1a43a61cc9aa6f5d2b35ba6d01f9898d1e2
* [x] アクティブウィンドウ切り替えの検出
* [X] ウィンドウ全体スクロール https://github.com/shouh/scripts/commit/0861910415c238bc94445b61383ffa8adb01210d
* [x] CUI 
* -------- enhancement --------
* [X] 使いやすさ向上委員会
* [x] :x: ConEmu のウィンドウサイズが自動補正されるのを解消する https://github.com/shouh/issueet/issues/1051
* [x] ソート後、自動的にactivecenterを適用する https://github.com/shouh/scripts/commit/ce1ef00fdafb7cf87446aac6a69ebd05c866f262
* [x] activecenter高速化 https://github.com/shouh/scripts/commit/4cadcad120a127f13aa509f3176de47800965641
* [ ] ウィンドウ複数枚の縦配置
* [ ] 隣のウィンドウを activecenter する
* [ ] win + cursor 系のショートカットキーをサポートする
* [ ] CLI
  * [ ] カスタムフィルター
    * [ ] caption 部分一致
    * [ ] classname 部分一致
    * [ ] その他設定値(スクロール量)を適宜、とりあえず例として何か一つ組み込む
  * [x] 標準出力系はデバッグオプションに押し込む https://github.com/shouh/scripts/commit/b1fd83e7bcbfade878b91c742c1ad29b3e0f98a5

**Comment by shouh** [comment]
# ウィンドウを並べるアルゴリズム
* IN
  * hwnds(対象ウィンドウハンドルのリスト)。
* Parameters
  * next_margin(pixel)
  * y-position(string)
    0. center
    0. asc(昇順。逆カスケード)
    0. ~~desc(降順。カスケード)~~ ウィンドウ隠れるので要らん

**Comment by shouh** [comment]
# デスクトップ上ホイール関連
ドラッグは https://github.com/shouh/scripts/commit/af901e62a067bb474e1a912d870a6cb942d18102 で実装した。

ダブクリは条件分岐とフラグが乱れるのでやりたくないなあ。シングルクリックにしちゃう？

**Comment by shouh** [comment]
# アクティブウィンドウ検出および基点スクロール
基本は「アクティブウィンドウが中央になるようにスクロールする」だが、適用条件が結構複雑。

* 管理対象外ウィンドウがアクティブだった場合は何もしない
* アクティブウィンドウがメインディスプレイ中に見えている場合は何もしない
* altab ツール自体が管理対象になるのは避けたい

**Comment by shouh** [comment]
# 使いやすさ向上委員会
* :file_folder: 操作
  * :file_folder: グローバル
    * デスクトップホイールクリック
    * デスクトップホイールドラッグ
    * アップエッジ
    * ダウンエッジ
    * :file_folder: ジェスチャー
      * アップエッジ to ダウンエッジ
      * ダウンエッジ to アップエッジ
  * :file_folder: ウィンドウ
    * タイトルバーホイールクリック
    * タイトルバーホイールドラッグ(マニュアル)
    * :file_folder: タイトルバーホイールドラッグ(ディレクション)
      * アップ
      * レフト
      * ダウン
      * ライト

**Comment by shouh** [comment]
# 自動補正ウィンドウの取り扱いをどうするか
ConEmu 以外にも存在する可能性は十分ある。個別に対応するのはしんどいし、そもそも対応されないケースもあるので……仕様にするか。つまり、

* 自動補正はソフトウェア側でかかってるので、こちらではなんともなりません
* 自動補正搭載ウィンドウを管理したくない場合は、最小化する等して対応してください

**Comment by shouh** [comment]
# 代案ブレスト
* 純粋にデスクトップスクロールのみにする
* window_slider でいうところの push や pull を取り入れる

**Comment by shouh** [comment]
# winsort 試用まとめなど
* ソート時に毎回最左ウィンドウが 0,0 になるので、右側ウィンドウ開いてた時に余分なスクロールが必要で手間かかる
  * アルゴリズム
    0. ソート時、アクティブウィンドウの rect を記録しておく
    0. ソート後、0, 0 基点になるので、記録してた rect を元にデスクトップスクロールする
* activecenter がまだ遅いかなあ...
  * :memo: タスクバークリック + ダウンエッジなら比較的早そう。あとメインディスプレイ内のみじゃなくて常に activecenter する、でもいいかも。

**Comment by shouh** [comment]
# GetCursorPos でエラー
```python
[winsort - window manager prototype ・ Issue #933 ・ shouh/issueet - Mozilla Firefox](MozillaWindowClass) pos(1558, 102) size(1065 x 876)
Traceback (most recent call last):
  File "C:\work\github\shouh\scripts\pathed_commands\winsort.py", line 323, in <module>
    if cornerstate.is_on_up():
  File "C:\work\github\shouh\scripts\pathed_commands\winsort.py", line 38, in is_on_up
    _, y = mouselib.get_cursorpos()
  File "C:\work\github\shouh\scripts\pathed_commands\mouselib.py", line 7, in get_cursorpos
    mx, my = win32api.GetCursorPos()
pywintypes.error: (5, 'GetCursorPos', 'アクセスが拒否されました')
```

**Comment by shouh** [comment]
# 隣のウィンドウを取得する
`WindowSorter` クラスをいじる。`next_window()` なるメソッドを作る。こいつに `sort_windows()` の戻り値と現在のアクティブウィンドウハンドルを与えて呼び出すと、そのアクティブの隣のウィンドウを計算してそのハンドルを返す。

**Comment by shouh** [comment]
#  ウィンドウ複数枚の縦配置
理屈はわかるけど、処理が煩雑なのでいかにシンプルに実装するかの勝負になりそう。。。

**Comment by shouh** [comment]
# 使い心地改善委員会part2
* [ ] アップエッジによるactivecenterうざいので消したい
* [ ] ホイクリなしでスクロールしたい(アップエッジ上での左右移動で全体スクロールとか)

**Comment by shouh** [comment]
# リファクタリング
## グローバルベースの適宜関数化クラス化アプローチにする
```
	exit(Winsort.main())

	↓

	class Winsort:
		def main(self):
			activewnd = ActiveWindowController()
			mousestate = MouseState(activewnd)
			while True:
				activewnd.update()
				mousestate.update()

trigger一覧
・デスクトップ上でホイドラ
・デスクトップ上でホイクリ
・エッジ上でエッジ上のまま左右移動
・エッジ上でホイクリ
---
is_desktop
is_wheel_clicked
is_on_edge
is_wheel_clicked_on_edge? <== 複合イベント。どこでどう扱えばよい？
is_being_draged

↓

これらパーツは複数回呼び出すことができる。
つまり一度の呼び出しで内部状態は完結する。
ので、複合イベントはこうなる。

	if is_on_edge():
		if is_wheel_clicked():
			...
			continue
	if is_wheel_clicked():
		...
```

**Comment by shouh** [comment]
# 反省
ぶっちゃけ **これあんま使い勝手良くない** よね。ただタイル状に並べて同時に動かせるのが気持ちいいだけで。

じゃあ何があれば使い勝手良くなる？どうしたいの？ …… アクティブじゃないウィンドウを探す手間を減らしたい。タスクバー見て探してクリックよりももっと楽に。結局 **独自の altab が必要になる** のかな。
