### ISSUE TITLE
winap - ウィンドウ表示状態を一時的に保存し、あとで復元する

### ISSUE THREAD

**Issue by shouh** [shouh/issueet#945]
# 背景
https://github.com/shouh/issueet/issues/933 で手動テストしたい場合にいちいち元に戻すのが面倒なのよ。

# 名前
WINdow sNAP shot = winap。

# 方針
**できるだけシンプルに**

保存時の名前指定とか要らない。一時的に保存したいだけなのだから保存件数はせいぜい数件のはず。

# TODO
* [X] 状態をファイルにprependする https://github.com/shouh/scripts/commit/5dee4460d0f91aec40a54d12857680ebb8869b1e
* [x] 保存した状態を専用データ構造に読み込む
  * https://github.com/shouh/scripts/commit/39e9b7f600b6e5433be2df9e01dee1277275d5a7
  * [x] 指定状態の削除も欲しい(ファイル保存に反映できるところまで)
* [x] getch を用いた即入力型 CLI
* [x] コマンドライン引数などの設計
* ---- ひととおりでけた
  * from https://github.com/shouh/scripts/commit/7314730b232d31fccbfb15c5625681ca61cfdd59 to https://github.com/shouh/scripts/commit/87a76bb435be811077d6ba3b2f94750d5e498ac1 このへん
* [X] :x: 保存内容のマニュアル削除
  * 実装的にかなり面倒くさいので挫折。直接ファイルいじってください。
* [x] ConEmu のウィンドウも復元したい
  * 注意事項追加: **ConEmu 自身で winap.py を立ち上げると、自身は Move できない**
* [x] 存在しないウィンドウハンドルがあるときに move すると `pywintypes.error: (1400, 'MoveWindow', ウィンドウ ハンドルが無効です。')` になる件 https://github.com/shouh/scripts/commit/9792b307a41d0adbf6cc5b8aac7494ac29fa705f
* [x] 選択肢を上書きで表示する https://github.com/shouh/scripts/commit/d3441f2bda66965af9fbcb055c08dc4097550649
* [x] remove の表示内容は removed と remain の二つ https://github.com/shouh/scripts/commit/01ffe9e79633047df22a39588dbd371ba4c0dbc7
* [x] 手動 remove の実装(複数選択制にして最後にまとめて消す、なら実装上できる) https://github.com/shouh/scripts/commit/86f593a9716f0deb4ed0a2e5e24f28c35967ec12
* [x] auto action の実装
* ---- ひととおりでけた
* [x] しばらく試用してみて問題無ければクローズ

**Comment by shouh** [comment]
* 非常駐
* path に通してコマンド or ファイル名指定して実行から使う
* UI は CLI
* 機能
  * 現在のウィンドウ状態を保存する(名前も付けられる)
  * 指定したウィンドウ状態を復元する
  * 復元ページネーション … 次/前の設定を復元、を繰り返せるUI。enterで確定、escで元に戻す
  * 指定したウィンドウ状態を削除する
* データ
  * hwnd
  * rect
  * 書式は `(hwnd), (xpos), (ypos), (xsize), (yize)` でいいかな
  * 同ディレクトリにテキストファイルで保存すればええか
* 例外条件
  * コマンドラインで指定する。and条件。
  * `--under-area 1000` 面積1000以下のウィンドウは除外
  * `--classname hoge` クラス名に hoge を含むウィンドウは除外

**Comment by shouh** [comment]
# 状態保存
以下のウィンドウ達が保存されます。よろしいですか？y/n。nだと終了する。コマンドライン引数工夫して出なおせ。

yだと保存フェーズ。まずは設定名入力させて(デフォルトは適当に `state_XXX`)、んで保存。こんな設定で保存したよってのも表示させたいかな。

**Comment by shouh** [comment]
# 状態復元
引数無し。getch で対話的に実施。

```
$ restore
最新日付から順に状態を表示する...
...
(restore)> z  ;左の状態を復元
(restore)> x  ;右の状態を復元
(restore)> space  ;元の状態に戻す.
(restore)> enter ;終了
(restore)> esc ; キャンセルして終了(space + enter)
```

引数有。部分一致をダイレクトに。複数一致する場合は上記と同じUIを。

```
$ restore hoge
```

**Comment by shouh** [comment]
# 保存データ
一ファイルに収めたい。

```
160705_151238 (hwnd), (xpos), (ypos), (xsize), (yize)
160705_151238 (hwnd), (xpos), (ypos), (xsize), (yize)
160705_151238 (hwnd), (xpos), (ypos), (xsize), (yize)
...
```

内部では `yymmdd_hhmmss` をキーにした辞書を都度つくる。

**Comment by shouh** [comment]
# ConEmu 問題
GetAncestor では効果なし。

[spuit.py](https://github.com/shouh/scripts/blob/master/pathed_commands/spuit.py) レベルでも問題無し。modifier move でも普通に操作できる。ってことは、listup_windows() がおかしいのか。もっというと FindWindowEx およびそのラッパー達。

**Comment by shouh** [comment]
# :x: Carriage return で一行見せ
以下のように選択肢出力を一行完結させたいのだが。

before

```
$ winap --load
Select:'z'|'x', Action:'c', Quit:'q'.
<<CURRENT_STATUS>>160719_161424 160719_161123 160719_160351 160719_155518 CURRENT_STATUS <<160719_161424>>160719_161123 160719_160351 160719_155518
...
```

after

```
$ winap --load
Select:'z'|'x', Action:'c', Quit:'q'.
CURRENT_STATUS <<160719_161424>>160719_161123 160719_160351 160719_155518
...

`sys.stdout.write('\r')` と `sys.stdout.flush()`  だけでは機能しないのなんで？間に getch() が入ってるから？いや関係無いだろ print じゃないんだし。

## 上手く行くスクリ
```python
# -*- coding: utf-8 -*-

from time import sleep
import sys

def barstr(gauge_num, limit=32):
    ret = ''

    ret += '['
    for i in range(gauge_num):
        ret += '#'
    for i in range(limit-gauge_num):
        ret += ' '
    ret += ']'

    return ret

limit = 32
for i in range(limit):
    bar = barstr(i, limit)
    sleep(0.05)

    #OK
    print bar,
    sys.stdout.write('\r')

    #OK
    #sys.stdout.write('%s\r' % bar)

    #NG
    #print '\r'
print '' # 上書きしないように入れておかないと.
print 'Finished.'
```
